# Generated by Django 3.2.8 on 2022-10-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Зарегестрированные пользователи', 'verbose_name_plural': 'Зарегестрированные пользователи'},
        ),
    ]
